# Generated by Django 4.1.4 on 2022-12-26 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("meal_type", models.IntegerField()),
                ("total_people_in", models.IntegerField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="InOutTimestamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("people_in", models.IntegerField()),
                ("people_out", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                (
                    "inout_key",
                    models.ForeignKey(
                        db_column="inout_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inout_timestamp",
                        to="stream.inout",
                    ),
                ),
            ],
        ),
    ]
