# Generated by Django 4.1.4 on 2022-12-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inouttimestamp",
            name="five_minutes",
            field=models.IntegerField(default=5),
        ),
    ]
