# Generated by Django 4.1.4 on 2022-12-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0002_inouttimestamp_five_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="inouttimestamp",
            name="meal_type",
            field=models.IntegerField(default=0),
        ),
    ]
