# Generated by Django 4.1.4 on 2022-12-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0003_inouttimestamp_meal_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="inouttimestamp", name="people_in",),
        migrations.RemoveField(model_name="inouttimestamp", name="people_out",),
        migrations.AddField(
            model_name="inouttimestamp",
            name="people",
            field=models.IntegerField(default=0),
        ),
    ]
