# Generated by Django 4.1.4 on 2022-12-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0004_remove_inouttimestamp_people_in_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InoutTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("people", models.IntegerField(default=0)),
                ("hour", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(model_name="inouttimestamp", name="time",),
        migrations.AlterField(
            model_name="inout",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="inouttimestamp",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
